from Importer.file_importer import FileImport
from Importer.cdli_corpus import CDLICorpus
f = FileImport('texts/cdli_corpus.txt')
c = CDLICorpus()
f.read_file()
#print(c._find_edition(f.file_lines))
#print(len(c._find_edition(f.file_lines)))
#print(c._find_cdli_number(f.file_lines))
#print(len(c._find_cdli_number(f.file_lines)))
#print(c._find_metadata(f.file_lines))
#print(len(c._find_metadata(f.file_lines)))
#print(c._find_transliteration(f.file_lines))
#print(len(c._find_transliteration(f.file_lines)))
#print()
c.ingest_text_file(f.file_lines)
#print(c.table_of_contents())
print(c.call_text('&P464358'))